import { NextResponse } from 'next/server'

import { createSupabaseUploadStore, deleteAudio } from '@/lib/server/mediaMutations'
import { assertAllowedOrigin } from '@/lib/server/origin'
import { HttpError, readSession, requireAdmin } from '@/lib/server/session'
import { getSupabaseAdmin } from '@/lib/server/supabaseAdmin'

function responseFor(error: unknown) { return error instanceof HttpError ? NextResponse.json({ error: error.message }, { status: error.status }) : NextResponse.json({ error: 'Audio request failed' }, { status: 500 }) }
function row(data: any) { return { id: data.id, title: data.title, author: data.author, date: data.date, audioPath: data.audio_path, audioUrl: `/api/media/audio?path=${encodeURIComponent(data.audio_path)}`, duration: data.duration, createdAt: data.created_at } }

export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { try { await assertAllowedOrigin(request); requireAdmin(await readSession(request.headers.get('cookie'))); const body = await request.json(); if (!body || typeof body.title !== 'string' || typeof body.author !== 'string' || typeof body.date !== 'string') throw new HttpError(400, 'Invalid audio metadata'); const { data, error } = await (await getSupabaseAdmin()).from('audio_messages').update({ title: body.title, author: body.author, date: body.date }).eq('id', (await params).id).select('*').maybeSingle(); if (error) throw new Error('Audio update failed'); if (!data) throw new HttpError(404, 'Audio not found'); return NextResponse.json(row(data)) } catch (error) { return responseFor(error) } }
export async function DELETE(request: Request, { params }: { params: Promise<{ id: string }> }) { try { await assertAllowedOrigin(request); requireAdmin(await readSession(request.headers.get('cookie'))); const id = (await params).id; const supabase = await getSupabaseAdmin(); const result = await deleteAudio(id, { deleteAudio: async (audioId) => { const found = await supabase.from('audio_messages').select('audio_path').eq('id', audioId).maybeSingle(); if (found.error) throw new Error('Audio query failed'); if (!found.data) throw new HttpError(404, 'Audio not found'); const deleted = await supabase.from('audio_messages').delete().eq('id', audioId); if (deleted.error) throw new Error('Audio delete failed'); return found.data.audio_path } }, await createSupabaseUploadStore()); return NextResponse.json(result) } catch (error) { return responseFor(error) } }
