import { NextResponse } from 'next/server'

import { YEARLY_BUCKET, createSupabaseUploadStore, databaseFirstDelete } from '@/lib/server/mediaMutations'
import { assertAllowedOrigin } from '@/lib/server/origin'
import { HttpError, readSession, requireAdmin } from '@/lib/server/session'
import { getSupabaseAdmin } from '@/lib/server/supabaseAdmin'
import { FIELD_LIMITS, fileField, readFormDataBody, REQUEST_LIMITS } from '@/lib/server/requestLimits'
import { requireYearlyOwnedItem, yearlyRouteYear, yearlySummaryId } from '@/lib/server/yearlyOwnership'

function responseFor(error: unknown) { return error instanceof HttpError ? NextResponse.json({ error: error.message }, { status: error.status }) : NextResponse.json({ error: 'Media request failed' }, { status: 500 }) }
function idFrom(value: string) { const id = Number(value); if (!Number.isSafeInteger(id) || id < 1) throw new HttpError(400, 'Invalid image id'); return id }
async function image(year: string, id: number) { const supabase = await getSupabaseAdmin(); const summaryId = await yearlySummaryId(supabase, year); const data = await requireYearlyOwnedItem(supabase, summaryId, 'image', id); return { supabase, summaryId, data } }

export async function PUT(request: Request, { params }: { params: Promise<{ year: string; imageId: string }> }) { try { await assertAllowedOrigin(request); requireAdmin(await readSession(request.headers.get('cookie'))); const values = await params; const year = yearlyRouteYear(values.year); const { supabase, summaryId, data } = await image(year, idFrom(values.imageId)); const form = await readFormDataBody(request, REQUEST_LIMITS.imageForm); const file = fileField(form.get('file'), { maximumBytes: FIELD_LIMITS.diaryImageBytes, mimeType: 'image/webp' }); await (await createSupabaseUploadStore()).upload(YEARLY_BUCKET, data.storage_path, file, { upsert: true, contentType: 'image/webp' }); const { data: updated, error } = await supabase.from('yearly_images').update({ updated_at: new Date().toISOString() }).eq('id', data.id).eq('yearly_summary_id', summaryId).select('id, storage_path, updated_at').single(); if (error) throw new Error('Yearly image metadata write failed'); return NextResponse.json({ id: updated.id, path: updated.storage_path, updatedAt: updated.updated_at }) } catch (error) { return responseFor(error) } }
export async function DELETE(request: Request, { params }: { params: Promise<{ year: string; imageId: string }> }) { try { await assertAllowedOrigin(request); requireAdmin(await readSession(request.headers.get('cookie'))); const values = await params; const year = yearlyRouteYear(values.year); const { supabase, summaryId, data } = await image(year, idFrom(values.imageId)); return NextResponse.json(await databaseFirstDelete(YEARLY_BUCKET, data.storage_path, async () => { const { error } = await supabase.from('yearly_images').delete().eq('id', data.id).eq('yearly_summary_id', summaryId); if (error) throw new Error('Yearly image metadata delete failed') }, await createSupabaseUploadStore())) } catch (error) { return responseFor(error) } }
