import { NextResponse } from 'next/server'
import { assertAllowedOrigin } from '@/lib/server/origin'
import { HttpError, readSession, requireAdmin } from '@/lib/server/session'
import { getSupabaseAdmin } from '@/lib/server/supabaseAdmin'
import { dateRangeFields, FIELD_LIMITS, readJsonBody, REQUEST_LIMITS, stringField } from '@/lib/server/requestLimits'
function responseFor(error: unknown) { return error instanceof HttpError ? NextResponse.json({ error: error.message }, { status: error.status }) : NextResponse.json({ error: 'Health request failed' }, { status: 500 }) }
function output(row: any) { return { id: row.id, condition: row.condition, startDate: row.start_date, endDate: row.end_date, color: row.color, created_at: row.created_at } }
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { try { await assertAllowedOrigin(request); requireAdmin(await readSession(request.headers.get('cookie'))); const body = await readJsonBody(request, REQUEST_LIMITS.healthJson) as Record<string, unknown> | null; const range = dateRangeFields(body?.startDate, body?.endDate); const values = { condition: stringField(body?.condition, 'health condition', { min: 1, max: FIELD_LIMITS.healthCondition, trim: true }), start_date: range.start, end_date: range.end, color: stringField(body?.color, 'health color', { min: 1, max: 32 }) }; const { data, error } = await (await getSupabaseAdmin()).from('health_conditions').update(values).eq('id', (await params).id).select('*').maybeSingle(); if (error) throw new Error('Health write failed'); if (!data) throw new HttpError(404, 'Health condition not found'); return NextResponse.json(output(data)) } catch (error) { return responseFor(error) } }
export async function DELETE(request: Request, { params }: { params: Promise<{ id: string }> }) { try { await assertAllowedOrigin(request); requireAdmin(await readSession(request.headers.get('cookie'))); const { error } = await (await getSupabaseAdmin()).from('health_conditions').delete().eq('id', (await params).id); if (error) throw new Error('Health delete failed'); return new Response(null, { status: 204 }) } catch (error) { return responseFor(error) } }
