export interface ImportantEvent { id: string | number; startDate: string; endDate: string; description: string }
export interface AIAnalysisOpinion { id: string | number; content: string; analysis: string; created_at?: string }
export interface AIAnalysisSection { id: string | number; title: string; content: string; opinions: AIAnalysisOpinion[]; created_at?: string }
export interface InvestmentImage { id: string | number; url: string; alt: string; path: string }
export interface YearlySummary { year: string; importantEvents: ImportantEvent[]; aiAnalyses: AIAnalysisSection[]; investmentImages: InvestmentImage[] }

const cache: Record<string, YearlySummary | null> = {}
async function request<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(path, init); if (!response.ok) { const body = await response.json().catch(() => null) as { error?: string } | null; throw new Error(body?.error ?? 'Yearly summary request failed') }; return response.status === 204 ? undefined as T : response.json() as Promise<T> }
function clear(year: string) { delete cache[year] }

export async function fetchYearlySummary(year: string): Promise<YearlySummary | null> { if (year in cache) return cache[year]; const data = await request<YearlySummary | null>(`/api/yearly-summaries/${encodeURIComponent(year)}`); cache[year] = data; return data }
export async function fetchInvestmentImages(year: string): Promise<InvestmentImage[]> { return (await fetchYearlySummary(year))?.investmentImages ?? [] }
export async function saveYearlySummary(year: string, _data: YearlySummary): Promise<YearlySummary> { clear(year); const result = await request<ImportantEvent>(`/api/yearly-summaries/${encodeURIComponent(year)}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'event.create', event: { startDate: `${year}-01-01`, endDate: `${year}-01-01`, description: '' } }) }); await deleteImportantEvent(Number(result.id), year); const summary = await fetchYearlySummary(year); if (!summary) throw new Error('Failed to create yearly summary'); return summary }
export async function addImportantEvent(year: string, event: Omit<ImportantEvent, 'id'>): Promise<ImportantEvent> { clear(year); return request(`/api/yearly-summaries/${encodeURIComponent(year)}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'event.create', event }) }) }
export async function updateImportantEvent(id: number, event: Omit<ImportantEvent, 'id'>, year = new Date().getFullYear().toString()): Promise<ImportantEvent> { clear(year); return request(`/api/yearly-summaries/${year}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ kind: 'event', id, value: event }) }) }
export async function deleteImportantEvent(id: number, year = new Date().getFullYear().toString()): Promise<void> { clear(year); await request(`/api/yearly-summaries/${year}?kind=event&id=${id}`, { method: 'DELETE' }) }
export async function addAIAnalysisSection(year: string, section: Omit<AIAnalysisSection, 'id' | 'opinions'>): Promise<AIAnalysisSection> { clear(year); return request(`/api/yearly-summaries/${year}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'section.create', section }) }) }
export async function updateAIAnalysisSection(id: number, section: Omit<AIAnalysisSection, 'id' | 'opinions'>, year = new Date().getFullYear().toString()): Promise<AIAnalysisSection> { clear(year); return request(`/api/yearly-summaries/${year}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ kind: 'section', id, value: section }) }) }
export async function deleteAIAnalysisSection(id: number, year = new Date().getFullYear().toString()): Promise<void> { clear(year); await request(`/api/yearly-summaries/${year}?kind=section&id=${id}`, { method: 'DELETE' }) }
export async function addAIAnalysisOpinion(sectionId: number, opinion: Omit<AIAnalysisOpinion, 'id'>, year = new Date().getFullYear().toString()): Promise<AIAnalysisOpinion> { clear(year); return request(`/api/yearly-summaries/${year}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'opinion.create', sectionId, opinion }) }) }
export async function updateAIAnalysisOpinion(id: number, opinion: Omit<AIAnalysisOpinion, 'id'>, year = new Date().getFullYear().toString()): Promise<AIAnalysisOpinion> { clear(year); return request(`/api/yearly-summaries/${year}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ kind: 'opinion', id, value: opinion }) }) }
export async function deleteAIAnalysisOpinion(id: number, year = new Date().getFullYear().toString()): Promise<void> { clear(year); await request(`/api/yearly-summaries/${year}?kind=opinion&id=${id}`, { method: 'DELETE' }) }
export async function addInvestmentImage(year: string, file: File): Promise<InvestmentImage> { clear(year); const form = new FormData(); form.set('file', file); const result = await request<{ id: string | number; path: string; updatedAt?: string }>(`/api/yearly-summaries/${year}/images`, { method: 'POST', body: form }); return { id: result.id, path: result.path, alt: `Yearly image ${result.id}`, url: `/api/media/yearly?path=${encodeURIComponent(result.path)}&v=${encodeURIComponent(result.updatedAt ?? '')}` } }
export async function updateInvestmentImage(id: number, file: File, year = new Date().getFullYear().toString()): Promise<InvestmentImage> { clear(year); const form = new FormData(); form.set('file', file); const result = await request<{ id: string | number; path: string; updatedAt?: string }>(`/api/yearly-summaries/${year}/images/${id}`, { method: 'PUT', body: form }); return { id: result.id, path: result.path, alt: `Yearly image ${result.id}`, url: `/api/media/yearly?path=${encodeURIComponent(result.path)}&v=${encodeURIComponent(result.updatedAt ?? '')}` } }
export async function deleteInvestmentImage(id: number, year = new Date().getFullYear().toString()): Promise<{ residualPaths: string[] }> { clear(year); return request(`/api/yearly-summaries/${year}/images/${id}`, { method: 'DELETE' }) }
