-- Read-only, fail-closed postflight for the anonymous-message exception.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname='anonymous_messages' AND c.relrowsecurity) THEN RAISE EXCEPTION 'RLS is disabled on anonymous_messages'; END IF;
  IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace CROSS JOIN LATERAL aclexplode(COALESCE(c.relacl, acldefault('r', c.relowner))) x WHERE n.nspname='public' AND c.relname='anonymous_messages' AND x.grantee=0) THEN RAISE EXCEPTION 'PUBLIC privilege remains on anonymous_messages'; END IF;
  IF (SELECT count(*) FROM pg_policies WHERE schemaname='public' AND tablename='anonymous_messages') <> 2 THEN RAISE EXCEPTION 'anonymous_messages must have exactly two policies'; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='anonymous_messages' AND policyname='Allow anon read access' AND roles=ARRAY['anon']::name[] AND cmd='SELECT' AND qual='true') THEN RAISE EXCEPTION 'anon SELECT policy is missing or changed'; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='anonymous_messages' AND policyname='Allow anon insert access' AND roles=ARRAY['anon']::name[] AND cmd='INSERT' AND with_check='true') THEN RAISE EXCEPTION 'anon INSERT policy is missing or changed'; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.anonymous_messages'::regclass AND conname='anonymous_messages_content_length_check' AND convalidated AND pg_get_constraintdef(oid,true)='CHECK (char_length(btrim(content)) >= 2 AND char_length(btrim(content)) <= 1000)') THEN RAISE EXCEPTION 'trimmed 2-1000 constraint is missing or changed'; END IF;
  IF NOT has_table_privilege('anon','public.anonymous_messages','SELECT') OR NOT has_table_privilege('anon','public.anonymous_messages','INSERT') OR has_table_privilege('anon','public.anonymous_messages','UPDATE') OR has_table_privilege('anon','public.anonymous_messages','DELETE') THEN RAISE EXCEPTION 'anon privilege set is incorrect'; END IF;
  IF has_table_privilege('authenticated','public.anonymous_messages','SELECT') OR has_table_privilege('authenticated','public.anonymous_messages','INSERT') OR has_table_privilege('authenticated','public.anonymous_messages','UPDATE') OR has_table_privilege('authenticated','public.anonymous_messages','DELETE') THEN RAISE EXCEPTION 'authenticated retains anonymous-message privilege'; END IF;
  IF NOT has_table_privilege('service_role','public.anonymous_messages','SELECT') OR NOT has_table_privilege('service_role','public.anonymous_messages','INSERT') OR NOT has_table_privilege('service_role','public.anonymous_messages','UPDATE') OR NOT has_table_privilege('service_role','public.anonymous_messages','DELETE') THEN RAISE EXCEPTION 'service_role lost an anonymous-message CRUD privilege'; END IF;
END $$;
