import { NextResponse } from 'next/server'

import { assertAllowedOrigin } from '@/lib/server/origin'
import { HttpError, readSession, requireAdmin } from '@/lib/server/session'
import { getSupabaseAdmin } from '@/lib/server/supabaseAdmin'

function responseFor(error: unknown) { return error instanceof HttpError ? NextResponse.json({ error: error.message }, { status: error.status }) : NextResponse.json({ error: 'Yearly summary request failed' }, { status: 500 }) }
function yearFrom(year: string) { if (!/^\d{4}$/u.test(year)) throw new HttpError(400, 'Invalid year'); return year }
function event(row: any) { return { id: row.id, startDate: row.start_date, endDate: row.end_date, description: row.description } }
function opinion(row: any) { return { id: row.id, content: row.content, analysis: row.analysis, created_at: row.created_at } }
function section(row: any) { return { id: row.id, title: row.title, content: row.content, opinions: (row.ai_analysis_opinions ?? []).sort((a: any, b: any) => String(a.created_at).localeCompare(String(b.created_at))).map(opinion), created_at: row.created_at } }

export async function GET(_request: Request, { params }: { params: Promise<{ year: string }> }) {
  try { const year = yearFrom((await params).year); const supabase = await getSupabaseAdmin(); const { data: summary, error } = await supabase.from('yearly_summaries').select('id').eq('year', year).maybeSingle(); if (error) throw new Error('Yearly summary query failed'); if (!summary) return NextResponse.json(null); const [events, sections, images] = await Promise.all([supabase.from('important_events').select('*').eq('yearly_summary_id', summary.id).order('start_date'), supabase.from('ai_analysis_sections').select('*, ai_analysis_opinions(*)').eq('yearly_summary_id', summary.id).order('created_at'), supabase.from('yearly_images').select('*').eq('yearly_summary_id', summary.id).order('created_at')]); if (events.error || sections.error || images.error) throw new Error('Yearly summary query failed'); return NextResponse.json({ year, importantEvents: (events.data ?? []).map(event), aiAnalyses: (sections.data ?? []).map(section), investmentImages: (images.data ?? []).map((image: any) => ({ id: image.id, path: image.storage_path, alt: `Yearly image ${image.id}`, url: `/api/media/yearly?path=${encodeURIComponent(image.storage_path)}&v=${encodeURIComponent(image.updated_at ?? '')}` })) }) } catch (error) { return responseFor(error) }
}

export async function POST(request: Request, { params }: { params: Promise<{ year: string }> }) {
  try {
    await assertAllowedOrigin(request); requireAdmin(await readSession(request.headers.get('cookie'))); const year = yearFrom((await params).year); const body = await request.json(); const supabase = await getSupabaseAdmin()
    let { data: summary, error } = await supabase.from('yearly_summaries').select('id').eq('year', year).maybeSingle(); if (error) throw new Error('Yearly summary query failed'); if (!summary) { const created = await supabase.from('yearly_summaries').insert({ year }).select('id').single(); if (created.error) throw new Error('Yearly summary write failed'); summary = created.data }
    if (body?.action === 'event.create') { const { data, error: writeError } = await supabase.from('important_events').insert({ yearly_summary_id: summary.id, start_date: body.event.startDate, end_date: body.event.endDate, description: body.event.description }).select('*').single(); if (writeError) throw new Error('Yearly event write failed'); return NextResponse.json(event(data), { status: 201 }) }
    if (body?.action === 'section.create') { const { data, error: writeError } = await supabase.from('ai_analysis_sections').insert({ yearly_summary_id: summary.id, title: body.section.title, content: body.section.content }).select('*').single(); if (writeError) throw new Error('Yearly section write failed'); return NextResponse.json({ ...section(data), opinions: [] }, { status: 201 }) }
    if (body?.action === 'opinion.create') { const { data, error: writeError } = await supabase.from('ai_analysis_opinions').insert({ ai_analysis_section_id: body.sectionId, content: body.opinion.content, analysis: body.opinion.analysis }).select('*').single(); if (writeError) throw new Error('Yearly opinion write failed'); return NextResponse.json(opinion(data), { status: 201 }) }
    throw new HttpError(400, 'Invalid yearly summary action')
  } catch (error) { return responseFor(error) }
}

export async function PATCH(request: Request, { params }: { params: Promise<{ year: string }> }) { try { await assertAllowedOrigin(request); requireAdmin(await readSession(request.headers.get('cookie'))); yearFrom((await params).year); const body = await request.json(); const supabase = await getSupabaseAdmin(); const tables: Record<string, string> = { event: 'important_events', section: 'ai_analysis_sections', opinion: 'ai_analysis_opinions' }; const table = tables[body?.kind]; if (!table || !Number.isSafeInteger(body?.id)) throw new HttpError(400, 'Invalid yearly summary update'); const values = body.kind === 'event' ? { start_date: body.value.startDate, end_date: body.value.endDate, description: body.value.description } : body.kind === 'section' ? { title: body.value.title, content: body.value.content } : { content: body.value.content, analysis: body.value.analysis }; const { data, error } = await supabase.from(table).update(values).eq('id', body.id).select('*').maybeSingle(); if (error) throw new Error('Yearly summary update failed'); if (!data) throw new HttpError(404, 'Yearly summary item not found'); return NextResponse.json(body.kind === 'event' ? event(data) : body.kind === 'section' ? { ...section(data), opinions: [] } : opinion(data)) } catch (error) { return responseFor(error) } }
export async function DELETE(request: Request, { params }: { params: Promise<{ year: string }> }) { try { await assertAllowedOrigin(request); requireAdmin(await readSession(request.headers.get('cookie'))); yearFrom((await params).year); const url = new URL(request.url); const kind = url.searchParams.get('kind'); const id = Number(url.searchParams.get('id')); const tables: Record<string, string> = { event: 'important_events', section: 'ai_analysis_sections', opinion: 'ai_analysis_opinions' }; if (!tables[kind ?? ''] || !Number.isSafeInteger(id)) throw new HttpError(400, 'Invalid yearly summary delete'); const { error } = await (await getSupabaseAdmin()).from(tables[kind!]).delete().eq('id', id); if (error) throw new Error('Yearly summary delete failed'); return new Response(null, { status: 204 }) } catch (error) { return responseFor(error) } }
